### ISSUE TITLE
Cursor position row/col in status bar text is black on grey and hard to see

### ISSUE THREAD

**Issue by bedge** [rogerdudler/eclipse-ui-themes#24]
I couldn't find where to set this explicitly, but I would think that a manual override shouldn't be necessary when using a complete re-skin theme.

**Comment by agatti** [comment]
Probably I'm a little late to the party, but adding:

``` css
#org-eclipse-ui-StatusLine {
    color: #999;
}
```

seems to fix it for me.  I'll probably make a pull request later for this.
